DROP TABLE IF EXISTS TEACHER;

CREATE TABLE TEACHER (
    ID VARCHAR(100) PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    SURNAME VARCHAR(200) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    LAST_UPDATE_DATE TIMESTAMP NOT NULL);
